JoneBlogBundle_post:
    resource: "@JoneBlogBundle/Resources/config/routing/post.yml"
    prefix:   /post
        
JoneBlogBundle_aboutus:
    resource: "@JoneBlogBundle/Resources/config/routing/aboutus.yml"
    prefix:   /about-us

JoneBlogBundle_contactus:
    resource: "@JoneBlogBundle/Resources/config/routing/contactus.yml"
    prefix:   /contact-us

JoneBlogBundle_property:
    resource: "@JoneBlogBundle/Resources/config/routing/property.yml"
    prefix:   /properties

JoneBlogBundle_gallery:
    resource: "@JoneBlogBundle/Resources/config/routing/gallery.yml"
    prefix:   /gallery

# src/Blogger/BlogBundle/Resources/config/routing.yml
JoneBlogBundle_homepage:
    pattern:  /
    prefix: /
    defaults: { _controller: JoneBlogBundle:Page:index }
    requirements:
        _method:  GET


