parameters:
#    jone_blog.example.class: Jone\BlogBundle\Example

services:
#    jone_blog.example:
#        class: %jone_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
